### ISSUE TITLE
Looks Great!

### ISSUE THREAD

**Issue by borygo77** [arter97/SimpleMSR#1]
Hi @arter97 ! Can you tell me what value did you set to your prebuild kext ? ;)  Tried it on my machine but can't boot without charger. Any chance you can help me set my desired values ?

**Comment by arter97** [comment]
The prebuilt kext is the one built straight out of the source code, which is BD PROCHOT.

See SimpleMSR.hpp.

Your specific issue might be related to SDK mismatch and you may have to recompile them on your own with the latest Xcode and SDK.

**Comment by borygo77** [comment]
Thank you buddy :) Can you guide me how undervoltage can be achieved with your kext ? I would also like to change temps as my laptop is throttling like crazy from 75 degree :/  Throttlestop doing great job on my windows system here. 
I would be really grateful!

**Comment by arter97** [comment]
As mentioned in the README, the best guide I can find was at https://github.com/mihic/linux-intel-undervolt .

After figuring out which MSR values you're gonna write to 0x150, you can just add them to SimpleMSR.hpp.

**Comment by borygo77** [comment]
Simple as that 😂 I think I'm just too stupid yet to play with it 😕

Can you explain why you use those two? 

uint32_t msr_index[] = {
 uint64_t msr_value[] = {

Can you tell me how would you input this under voltage into you program? 
wrmsr 0x150 0x80000011F9A00000

**Comment by arter97** [comment]
Let's take "Undervolt GPU by 125mV and everything else by 150mV" from that page as an example.

You should change SimpleMSR.hpp to:

```
static const uint32_t msr_index[] = {
    0x150,
    0x150,
    0x150,
    0x150,
    0x150
};
static const uint64_t msr_value[] = {
    0x80000011ecc00000,
    0x80000111f0000000,
    0x80000211ecc00000,
    0x80000311ecc00000,
    0x80000411ecc00000
};
```

**Comment by borygo77** [comment]
Your the man!
Thanks a mill! Think now I'm gonna figure it out 😊

**Comment by borygo77** [comment]
Got this going alright! :) Thank you!

> WRMSR 150 with value 0x8000001000000000
RDMSR 150 returns value 0xf1000000
CPU voltage offset: -120mv
WRMSR 150 with value 0x8000011000000000
RDMSR 150 returns value 0xf4c00000
GPU voltage offset: -90mv
WRMSR 150 with value 0x8000021000000000
RDMSR 150 returns value 0xf1000000
CPU Cache voltage offset: -120mv
WRMSR 150 with value 0x8000031000000000
RDMSR 150 returns value 0x0
System Agency offset: 0mv
WRMSR 150 with value 0x8000041000000000
RDMSR 150 returns value 0x0
Analogy I/O: 0mv
WRMSR 150 with value 0x8000051000000000
OC mailbox cmd failed
RDMSR 150 returns value 0x500000000
Digital I/O: 0mv
CPU BaseFreq: 2000, CPU MaxFreq(1/2/4): 4600/4500/4100 (mhz)  PL1: 15W PL2: 51W 
CPU Freq: 1.0ghz, Voltage: 0.5479v, Power:pkg 11.87w /core 7.82w,Temp: 61 c
